file_format: "1"
id: charybdis
name: Charybdis
type: shield
url: https://github.com/Bastardkb/Charybdis/
requires: [pro_micro]
features:
  - Keys
  - QWERTY
siblings:
  - charybdis_left
  - charybdis_right_standalone
  - charybdis_right_dongle
  - prospector_dongle
